import {
    Document,
    Packer,
    Paragraph,
    TextRun,
    Table,
    TableRow,
    TableCell,
    HeadingLevel,
    AlignmentType,
    BorderStyle,
    WidthType,
} from 'docx';

export interface GeneratedContent {
    title: string;
    sections: Section[];
}

export interface Section {
    heading?: string;
    paragraphs?: string[];
    table?: TableData;
}

export interface TableData {
    headers: string[];
    rows: string[][];
}

export async function buildDocx(content: GeneratedContent): Promise<Buffer> {
    const docChildren: (Paragraph | Table)[] = [];

    docChildren.push(
        new Paragraph({
            text: content.title,
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
        })
    );

    for (const section of content.sections) {
        if (section.heading) {
            docChildren.push(
                new Paragraph({
                    text: section.heading,
                    heading: HeadingLevel.HEADING_1,
                    spacing: { before: 300, after: 150 },
                })
            );
        }

        if (section.paragraphs) {
            for (const para of section.paragraphs) {
                docChildren.push(
                    new Paragraph({
                        children: [new TextRun({ text: para, size: 24 })],
                        spacing: { after: 150 },
                    })
                );
            }
        }

        if (section.table) {
            const { headers, rows } = section.table;
            const tableRows: TableRow[] = [];

            tableRows.push(
                new TableRow({
                    tableHeader: true,
                    children: headers.map(
                        (header) =>
                            new TableCell({
                                children: [
                                    new Paragraph({
                                        children: [
                                            new TextRun({
                                                text: header,
                                                bold: true,
                                                size: 22,
                                                color: 'FFFFFF',
                                            }),
                                        ],
                                        alignment: AlignmentType.CENTER,
                                    }),
                                ],
                                shading: { fill: '2563EB' },
                                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                            })
                    ),
                })
            );

            rows.forEach((row, rowIndex) => {
                tableRows.push(
                    new TableRow({
                        children: row.map(
                            (cell) =>
                                new TableCell({
                                    children: [
                                        new Paragraph({
                                            children: [new TextRun({ text: cell, size: 22 })],
                                        }),
                                    ],
                                    shading: { fill: rowIndex % 2 === 0 ? 'EFF6FF' : 'FFFFFF' },
                                    margins: { top: 60, bottom: 60, left: 120, right: 120 },
                                    borders: {
                                        top: { style: BorderStyle.SINGLE, size: 1, color: 'DBEAFE' },
                                        bottom: { style: BorderStyle.SINGLE, size: 1, color: 'DBEAFE' },
                                        left: { style: BorderStyle.SINGLE, size: 1, color: 'DBEAFE' },
                                        right: { style: BorderStyle.SINGLE, size: 1, color: 'DBEAFE' },
                                    },
                                })
                        ),
                    })
                );
            });

            docChildren.push(
                new Table({
                    rows: tableRows,
                    width: { size: 100, type: WidthType.PERCENTAGE },
                })
            );

            docChildren.push(new Paragraph({ spacing: { after: 200 } }));
        }
    }

    docChildren.push(
        new Paragraph({
            children: [
                new TextRun({
                    text: `Generated by Department Assistant · ${new Date().toLocaleDateString('en-IN', {
                        day: '2-digit',
                        month: 'long',
                        year: 'numeric',
                    })}`,
                    italics: true,
                    size: 18,
                    color: '9CA3AF',
                }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 400 },
        })
    );

    const doc = new Document({
        sections: [{ children: docChildren }],
        styles: {
            default: {
                document: {
                    run: { font: 'Calibri', size: 24 },
                },
            },
        },
    });

    return await Packer.toBuffer(doc);
}

export function parseLLMContent(raw: string): GeneratedContent {
    const cleaned = raw.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    try {
        return JSON.parse(cleaned) as GeneratedContent;
    } catch {
        throw new Error(`Could not parse LLM content as JSON: ${cleaned.slice(0, 200)}`);
    }
}